//тексты на рус и англ
const languages = {
  english: {
    name: "English",
    settings: 'Settings',
    theme: 'Theme',
    fieldSize: 'Field Size',
    fieldSizeMsg: "Size",
    difficultyLabel: 'Difficulty (Unique elements)',
    difficultyMsg: 'Difficulty',
    difficulties: {
        Easy: "Easy",
        Medium: "Medium",
        Hard: "Hard",
      },
    reset: 'Save and Reset',
    language: "Language",
    victoryMsg: "Victory! Yaay! Steps:",
    gameOverMsg: "Game Over!",
    returnMsg: "Welcome back!",
    gameModeLabel: "Game Mode",
    gameMode: {Classic: "Classic", Survival: "Survival",},
    survivalMsg: "Lifes left",   
    currentThemeMsg: "Current theme: ",
    pictures: {
                Fruits: "Fruits",
                Cars: "Cars",
                Nature: "Nature",
                Animals: "Animals",
                Emojis: "Emojis",
                Sports: "Sports",
                Food: "Food",
                Weather: "Weather",
                Sweets: "Sweets",
                Сlothes: "Сlothes",
                Spooky: "Spooky",
                Horoscope: "Horoscope",
                "18+": "18+",
                Music: "Music",
              },
  },
  
  russian: {
    name: "Русский",
    settings: 'Настройки',
    theme: 'Тема',
    fieldSize: 'Размер поля',
    fieldSizeMsg: "Поле",
    difficultyLabel: 'Сложность (Уникальные элементы)',
    difficultyMsg: 'Сложность',
    difficulties: {
        Easy: "Легко",
        Medium: "Средне",
        Hard: "Хардкор",
      },
    reset: 'Сохранение и Перезапуск',
    language: "Язык",
    victoryMsg: "Победа! Ураа! Шагов:",
    gameOverMsg: "Жизни кончились!",
    returnMsg: "Рады видеть тебя снова!",
    gameModeLabel: "Режим игры",
    gameMode: {Classic: "Обычный", Survival: "Выживание",},
    survivalMsg: "Осталось жизней",
    currentThemeMsg: "Выбрана тема: ",
    pictures: {
        Fruits: "Фрукты",
        Cars: "Машины",
        Nature: "Природа",
        Animals: "Животные",
        Emojis: "Эмодзи",
        Sports: "Спорт",
        Food: "Еда",
        Weather: "Погода",
        Sweets: "Сладости",
        Сlothes: "Одежда",
        Spooky: "Страшное",
        Horoscope: "Гороскоп",
        "18+": "18+",
        Music: "Музыка",
      },
  },
};

export default languages;